### ISSUE TITLE
What is the license

### ISSUE THREAD

**Issue by doertel-uib** [genericptr/fpTOML#1]
Hello Ryan Joseph,

we are interested to use your fpToml library (https://github.com/genericptr/fpTOML) in our project opsi.
opsi is an open source based client management system  (https://opsi.org)
In detail we like to add the possibility to manipulate existing toml files to our script interpreter opsi-script
which is written in FPC:
https://github.com/opsi-org/lazarus/tree/master/opsi-script

We understand that the code part, to write back modified toml data structures to a toml file, is missing.
Before we start to fill this gap we need to discuss your license.
We do not Understand the concrete Terms of your license:
"Copyright (c) 2020 by Ryan Joseph"
In oder that we can use your code in our project,
we need with this copyright an explicit personal permission to use this code inside of our project
or better a compatible license.
Our opsi-script is licensed with the AGPLv3+ license.
In order to use your library, it have to has a compatible license.
And (so sorry) the line: "Copyright (c) 2020 by Ryan Joseph" is not a compatible license.
Possible licenses would be for example 'public domain', 'MIT/X11', LGPL, GPLv2+, GPLv3
(https://en.wikipedia.org/wiki/License_compatibility
https://en.wikipedia.org/wiki/File:Floss-license-slide-image.svg
https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences )

Please tell me what kind of license you are thinking of to make it possible to use your library.

I hope for an answer.
Thank your

regards

detlef oertel
d.oertel(at)uib.de

**Comment by genericptr** [comment]
I just updated the license to be the same as the Free Pascal Compiler so that should be good for you. :)

yes I never did finish the final part which actually writes TOML back to text because I didn't need that myself. Are you going to try to do this yourself? I plan to do it eventually but I just haven't had the motivation so far yet.
